/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'eyal.kopelevich' at '8/16/17 3:36 PM' with Gradle 2.14.1
 *
 * @author eyal.kopelevich, @date 8/16/17 3:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
